version: "3.8"

services:
  grafana:
    image: grafana/grafana:10.4.0
    container_name: post-incident-proofs-grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SECURITY_ADMIN_USER=admin
    volumes:
      - ./dashboards:/etc/grafana/provisioning/dashboards
      - ./datasources:/etc/grafana/provisioning/datasources
      - grafana-storage:/var/lib/grafana
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:latest
    container_name: post-incident-proofs-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./alerts.yml:/etc/prometheus/alerts.yml
      - prometheus-data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/etc/prometheus/console_libraries"
      - "--web.console.templates=/etc/prometheus/consoles"
      - "--storage.tsdb.retention.time=200h"
      - "--web.enable-lifecycle"
    restart: unless-stopped

  loki:
    image: grafana/loki:latest
    container_name: post-incident-proofs-loki
    ports:
      - "3100:3100"
    volumes:
      - loki-data:/loki
    command: -config.file=/etc/loki/local-config.yaml
    restart: unless-stopped

  post-incident-proofs:
    build: .
    container_name: post-incident-proofs-app
    ports:
      - "8080:8080"
    environment:
      - LOG_LEVEL=INFO
      - HMAC_KEY_FILE=/app/keys/hmac.key
    volumes:
      - ./logs:/app/logs
      - ./keys:/app/keys
    depends_on:
      - prometheus
      - loki
    restart: unless-stopped

volumes:
  grafana-storage:
  prometheus-data:
  loki-data:
