name: Log Bug Report
description: Report a bug in the tamper-evident logging system
title: "[LOG BUG] "
labels: ["bug", "logging"]
assignees: []

body:
  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of the bug
      placeholder: Describe what happened and what you expected to happen
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How severe is this bug?
      options:
        - Critical - System crash or data loss
        - High - Major functionality broken
        - Medium - Minor functionality broken
        - Low - Cosmetic issue
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Log Output
      description: Relevant log output or error messages
      placeholder: Paste any relevant log output here
      render: shell

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Your environment details
      placeholder: |
        - OS: [e.g. Ubuntu 22.04]
        - Lean Version: [e.g. 4.7.0]
        - Lake Version: [e.g. 3.4.0]
        - Architecture: [e.g. x86_64]

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context about the problem
      placeholder: Add any other context about the problem here 