name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Lean
        run: |
          wget https://github.com/leanprover/lean4/releases/download/v4.7.0/lean-4.7.0-linux.tar.gz
          tar -xzf lean-4.7.0-linux.tar.gz
          echo "$PWD/lean-4.7.0-linux/bin" >> $GITHUB_PATH

      - name: Build
        run: |
          lake build

      - name: Test
        run: |
          lake exe tests

      - name: Security Tests
        run: |
          lake exe security

      - name: Observability Tests
        run: |
          lake exe observability

      - name: Comprehensive Validation
        run: |
          lake exe validate

  benchmark:
    name: Benchmark
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Lean
        run: |
          wget https://github.com/leanprover/lean4/releases/download/v4.7.0/lean-4.7.0-linux.tar.gz
          tar -xzf lean-4.7.0-linux.tar.gz
          echo "$PWD/lean-4.7.0-linux/bin" >> $GITHUB_PATH

      - name: Run Benchmarks
        run: |
          lake exe benchmarks

  security:
    name: Security Scan
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Security Scan
        uses: github/codeql-action/init@v3
        with:
          languages: lean

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
